-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'INVOICE_ISSUED';
ALTER TYPE "NotificationEvent" ADD VALUE 'PAYMENT_RECEIVED';
ALTER TYPE "NotificationEvent" ADD VALUE 'PAYMENT_PARTIAL';
ALTER TYPE "NotificationEvent" ADD VALUE 'INVOICE_PAID';
ALTER TYPE "NotificationEvent" ADD VALUE 'PAYMENT_FAILED';
