-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'WORK_ORDER_CREATED';
ALTER TYPE "NotificationEvent" ADD VALUE 'WORK_SCHEDULED';
ALTER TYPE "NotificationEvent" ADD VALUE 'WORK_STARTED';
ALTER TYPE "NotificationEvent" ADD VALUE 'WORK_WAITING_PARTS';
ALTER TYPE "NotificationEvent" ADD VALUE 'QUALITY_CHECK_REQUIRED';
ALTER TYPE "NotificationEvent" ADD VALUE 'WORK_COMPLETED';
ALTER TYPE "NotificationEvent" ADD VALUE 'ADDITIONAL_WORK_REQUIRED';
