-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'MAINTENANCE_UPCOMING';
ALTER TYPE "NotificationEvent" ADD VALUE 'MAINTENANCE_DUE';
ALTER TYPE "NotificationEvent" ADD VALUE 'MAINTENANCE_OVERDUE';
